### PR TITLE
Fit to width and height

### PR DESCRIPTION
**Pull request by programmer-ceds**
Add menu and short-cut commands to fit to height or width. For further details see PR #143 - which was closed due to difficulties resubmitting a PR that was started with HTTPS now that SSH is mandatory.

@clefebvre - see what you think regarding centring the scrolling if the menu keys are used - this submitted version uses the mouse position even when the menu is used.

### CODE REVIEW

**Comment by clefebvre** [comment]
The symbolic icons aren't symbolic. They appear as mono (gray) instead of changing based on the background color.

I think it might be because you're shipping png versions here.

**Comment by clefebvre** [comment]
ok confirmed, if I remove the pngs, the symbolics work well.

**Comment by clefebvre** [comment]
- You mixed up some code in this PR. For instance you're going back to BILINEAR.. 
- That webp change looks like it belongs in a different PR
- The PNG files need to be removed

**Comment by clefebvre** [comment]
I'll mark this as Next for inclusion in Mint 21.

I'm worried it might delay 20.3, especially since it requires new translations.

**Comment by programmer-ceds** [comment]
@clefebvre  - sorry about that - I forgot the step of comparing and merging my edited files with the latest versions downloaded (which as I created a new fork of course included all of the other changes that I was then unintentionally reverting!)

I have removed the png icons and uploaded the original copies of the Makefile.am files for the icon sizes for which I deleted the png files.

Hopefully all should now be right.

**Comment by clefebvre** [comment]
Quick review looks good, thanks @programmer-ceds.

**Pull request merged**
