### PR TITLE
Key 1 behaviour changes

### PR DESCRIPTION
**Pull request by programmer-ceds**
Fix registration problem when the '1' key is pressed towards the edge of zoomed to fit image that doesn't reach the edge of the window. This is described in more detail in issue #84.

Also causes the '1' key to toggle between 1:1 and zoomed to fit - useful when wanting to check the focus at different parts of the image - can use one finger to press the '1' key and the other hand to move the mouse. Much easier than having to press '1' and 'F' alternately. Again see issue 84 for details.

### CODE REVIEW

**Comment by programmer-ceds** [comment]
OK - first time trying this. What do I do now? I have made the changes suggested by the quality review but haven't yet uploaded the modified file. Is there a way of updating the individual file on GitHub in this pull request or do I have to delete the request and start a new one?

**Comment by icarter09** [comment]
@programmer-ceds all you need to do is update the file on your PR and then push that change. It will update in Github.

**Comment by programmer-ceds** [comment]
Thanks Isaac,

The file now seems to pass the Quality Review

Regards
Richard

**Comment by mtwebster** [comment]
Hi, I think this is ok, there's just one quirk in the behavior that I notice - 

If I zoom in to some section, and hit 1, it *fits* first, and I have to hit 1 again to actually have it go to 1:1.  The only time toggling behaves as I *think* it probably should is when we're simply toggling between fit and 1:1

I think maybe hitting 1 should *always* jump to 1:1 unless we're currently fitted, and then it can toggle.  I'm curious what you think - I think the toggle behavior is nice, but having to hit it twice if you're zoomed is a bit strange.

Thanks

**Comment by mtwebster** [comment]
Also, the automated code review can be a bit over-enthusiastic sometimes - we're definitely most interested in following the existing code style where the changes are being made.  But no tabs!

**Comment by programmer-ceds** [comment]
I may have used the odd tab but I have just downloaded the master version of xviewer-scroll-view.c to find that there are numerous tabs present in the code already. Are you saying that I need to convert all of these to spaces?

(I have now set xed to use spaces instead of tabs)

When I made the change some time ago I missed the way that priv->zoom stores the current zoom factor - so I will change the code to compare this value with 1.0 and only zoom to fit if this value is not already set to 1.0 (assuming that rounding errors allow for this)

If I remember correctly the middle mouse button in Zoner Photostudio 16 behaves in the way that I implemented the code that I submitted - but I agree that what you suggest is more logical.

One thing that I'm not sure about is when the 1 key is pressed when an image has been zoomed already (to less than 1:1) is what will happen to the registration of the zoomed image relative to the cursor position - if this is not maintained (so far as it can without moving the cursor) do you think that I should make the change? If so I will submit a further commit with this change.

**Comment by collinss** [comment]
You don't need to change all the tabs to spaces. Generally our rule of thumb is clean up the code where you're working, and leave the rest (so basically new or edited code). That keeps the commits clean so that it's easy to see what they're actually changing. A couple of us actually will change the whole file to spaces, but we usually do it as a separate commit for the reason I just mentioned.

**Comment by mtwebster** [comment]
I tested just now using ctrl-0 and it doesn't position the image to keep the relative mouse position.  What's weird is if the 'fitted' image ends up at less than 100%, it manages just fine.  But if you then zoom to other than fitted size, it stops working.

I would say that should work if possible.

**Comment by programmer-ceds** [comment]
I have changed the code as suggested so that if the image isn't zoomed 1:1 when the '1' key is pressed it zooms 1:1.

If the image has been zoomed in or out before pressing '1' then registration is preserved (as far as it can without moving the cursor) when the image is zoomed to 1:1. However, when pressing '1' again to return to zoom-to-fit I think that it is not normally possible to maintain registration without moving the curso (which I don't think that it should do)r. For the way in which I wanted to use the toggle to check the focus in various parts of an image I personally don't see the loss of registration in this situation as a problem. On the plus side when zooming to 1:1 the revised code has much better registration than the master version when near to the edge of a zoomed-to-fit image that doesn't fill the window.

**Comment by programmer-ceds** [comment]
If you want to proceed with this change then the keyboard shortcuts.page file should be updated to include the action of the '1' key.

I have edited help/C/shortcuts.page to add "Toggle between 1:1 and best fit".

I have also added Reload image '0' to the same table.

When I make the application this extra key entry seems to get copied into the shortcuts.page files for all of the translations.

Questions:

1. There is an earlier entry in the table for Ctrl+0 = "Actual size". I think that the comment for the '1' key should say 1:1 to link the key to what it does. How about the text for Ctrl+0 is changed to "Actual size (1:1)" ?

2. Some of the translations do have translated text in their shortcuts.page files am I correct in thinking that all of the .po files that have "Actual size" in them should have this string edited to "Actual size (1:1)" and "(1:1)" added to the translations in order that the translations are preserved - or is the process more complicated than this?

Let me know if I should make these changes and push the modified files.

**Comment by mtwebster** [comment]
I agree with the shortcut changes, except don't worry about creating new translations - we only try to avoid it when we're close to release, and things like breaking the strings up to preserve these often cause problems with different languages.

Did you forgot to commit the shortcut changes? I don't see them here.

**Comment by programmer-ceds** [comment]
I was waiting to edit the .po translation files until you were happy with the proposed text for the short-cut keys. By changing the text for Ctrl+0 from "Actual size" to "Actual size (1:1)" in the C/shortcuts.page all of the translations for "Actual size" would have been ignored ("Actual size" would have been displayed instead of the previous translation) so I also added " (1:1)" to the end of the translation of the string in the 18 .po files that contained translations.

I have now pushed the C/shortcuts.page and the 18 .po files

Having done a git commit -a I now see that I have a message about a number of conflicting files. I will look to see if I can resolve this (by removing the listed files from the commit?) but I might need a bit of help.

**Comment by icarter09** [comment]
@programmer-ceds have you corrected all the conflicting files?

**Comment by programmer-ceds** [comment]
Apologies I seem to have messed up. Having done a git commit -a GitHub showed a number of conflicting files which I tried to delete. It is still showing po/xviewer.pot as a conflicting file even though I deleted it. Also three of the CI checks are pending ("Your tests are queued behind your running builds") - not sure how to get out of this (I've still a lot to learn!)

**Comment by programmer-ceds** [comment]
OK, all 4 tests have now passed but there is still the conflict with po/xviewer.pot which I had deleted. The Resolve Conflicts button says that "the conflicts are too complex to resolve in the web editor"

**Comment by icarter09** [comment]
@programmer-ceds you should be able to fix the conflicts on your machine. Open up the file on your branch and the conflicts should be there asking to be resolved. What are you editing your files in/with?

**Comment by icarter09** [comment]
@programmer-ceds once you fix that commit or get that file deleted, let me know and i'll walk you down how to fix up your PR.

**Comment by programmer-ceds** [comment]
@icarter09 I'm not sure how to resolve the conflict. I deleted the file from the branch, as I did with the others which it complained about. The other conflicts have gone but I am left with the one for po/xviewer.pot.

All 4 of the checks passed, so I assume it is just this conflict to resolve.

**Comment by icarter09** [comment]
@programmer-ceds see if you can do a `git stash save "Stashing conflicting file to get PR fixed."`  Then run `git status` and that should hopefully show you have a clean slate to work with.

**Comment by programmer-ceds** [comment]
@icarter09 The stash command reports "No local changes to save"

The git status report contains no reference to po/xviewer.pot (or any other .pot files)

**Comment by programmer-ceds** [comment]
@icarter09 having done make clean, make, sudo make install the git status report now contains the line "deleted:    po/xviewer.pot" - I only attempted to delete this file on GitHub so has it fetched this status from the web-site?

**Comment by icarter09** [comment]
@programmer-ceds in order to add that file to git so it can be commited you have to run `git rm (name of the file to delete)`. That would put on the queue to then be commited. You can verify that with `git status`

**Comment by programmer-ceds** [comment]
@icarter09 I've reached the point where I have fetched and merged so that I can now push again. I've taken a copy of the offending po/xviewer.pot file from the master, added that to my local version, added it to git, commited and pushed - that seems to have resolved the error - just waiting for the 4 tests to run now.

**Comment by mtwebster** [comment]
Hi there is still a lot of changes here that shouldn't be, let's do the following (Don't worry no matter what I have all of your changes, so nothing will be lost if something happens.):

from the xviewer folder:
```
git reset --hard            # cancels any pending changes so you can switch branches
sudo git clean -fdx       # removes temp build files
git checkout master                  # puts you back on master branch temporarily
git branch -D Key1Behavior              # gets rid of your pull request branch (don't panic!)
git remote add mike git@github.com:mtwebster/xviewer.git       # adds my fork that has the backup***
git fetch mike             # makes sure you can pick individual commits from my fork
git checkout -b Key1Behavior          # recreate your pull request branch
git pull --rebase origin master            # makes sure you're up-to-date with the current mint xviewer repo
git cherry-pick 5adfbfd4fac544e5a82f9            # applies the backup to this branch
git commit --amend           # lets you edit the commit message to be your own

# Edit the commit message with whatever you want then save

# Test build and run to make sure it works

git push --force <yourbranchname> Key1Behavior      # updates the pull request in Github
```

*** - in the git remote add line, if you're not using ssh (you'll get an error if you try to fetch), do `git remote remove mike` and then `git remote add mike https://github.com/linuxmint/xviewer.git` instead

**Comment by programmer-ceds** [comment]
@mtwebster The command "git branch -D Key1Behavior" reported that branch Key1Behaviour wasn't found.  Carried on to the next step, which seemed successful but then the git fetch mike reported that permission was denied.

I wonder if it wouldn't be easier to delete the PR and fork and start again with a new fork - I have all of the files that I changed backed up.

**Comment by mtwebster** [comment]
Ah you spell behavior differently :)  My instructions left out the u 

See my note at the bottom for how to get around the permission denied (you must be using https to access github and not ssh)

Or you can make a new PR, it's no big deal, I just don't want you giving up

**Comment by programmer-ceds** [comment]
OK on to the next problem - the command git cherry-pick 5adfbfd4fac544e5a82f9 reports "fatal: bad revision '5adfbfd4fac544e5a82f9'"

I never give up until something is proved impossible (although I am going to have to stop for this evening in a few minutes but I will be back tomorrow).

**Comment by programmer-ceds** [comment]
@mtwebster I tried following your instructions again this morning but adding the 'u' into behavior - still no difference the cherrypick command still fails.

I did notice that the file referred to by the cherry pick command only contains the changes to the C/shortcuts.page and xviewer-scroll-view.c files - it does not include the changes to the 18 help/.po files that need to be changed if the translation of "Actual size (1:1)" is not to appear just as the English version thereby losing the translations of this phrase that have already been done (I have added " (1:1)" to the ends of the translated strings)

My local repository now has none of the changes although all of the changes still appear in the branch on GitHub but I do have backups of the changed files ;-)

Would the simplest thing be to delete this PR, delete my fork, re-fork and start a new attempt to get the 20 files (xviewer-scrol-view.c, help/C/shortcuts.page and the help/.po files for the 18 languages that have translations) uploaded?

**Comment by mtwebster** [comment]
Yes just do a new PR I suppose - I left out the modified po files on purpose - that shouldn't be part of the PR - they'll get re-translated on launchpad (all of our potfiles end up there to be seen by people on translation teams).  Just include the program changes and the shorcut page.

**Comment by programmer-ceds** [comment]
@mtwebster But if the C/shortcuts.page file changed "Actual size" to "Actual size (1:1)" (thereby linking this action to the description for the '1' key action) it will affect the existing translations. The modified files saved someone having to fix this in the future - assuming that they notice that the translation will no longer work - or does the translation process flag any untranslated strings?

Also, just to check before I further mess things up, to start a new PR do I simply close this one and then delete my fork?

**Comment by mtwebster** [comment]
The modified strings will become marked as untranslated (in other words, it will get noticed).  You can't be certain your fixes are appropriate for every language (They probably are in this case but I don't want to assume that).

Yes you can just start a new pr and close this.

**Comment by programmer-ceds** [comment]
@mtwebster OK, understood. Thanks for your help and patience.

**Pull request closed without merging**
